# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
jobs:
  hello:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo Hello Denis
      - run: echo Additional build step

  build:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - run: echo build step
      - run: mkdir build_output
      - run: touch build_output/compiled_output.txt
      - persist_to_workspace:
          root: build_output
          paths:
            - '*'

  test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - run: echo test step
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/compiled_output.txt

  deploy:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - run: echo deploy step
      - attach_workspace:
          at: ~/repo/workspace
      - run: ls ~/repo/workspace/compiled_output.txt

workflows:
    example-workflow:
      jobs:
        - node/test
        - hello:
            requires:
              - node/test

    build-test-deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test